services:
  remembr:
    build:
      context: .
    image: cuda12.9.1-python3.14.2:bookworm-slim-ros-humble-uv
    container_name: remembr
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/remembr
      - /tmp/.X11-unix:/tmp/.X11-unix

  remembr-gpu:
    extends:
      service: remembr
    container_name: remembr-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, graphics]
    profiles:
      - gpu
